#!/bin/bash
targetpath='/data/backup'  # 备份目录
nowtime=$(date -d '-7 days' "+%Y%m%d") #只能删除7天前的1天的数据
if [ -d "${targetpath}/${nowtime}/" ]
then
  rm -rf "${targetpath}/${nowtime}/"
  echo "=======${targetpath}/${nowtime}/===删除完毕=="
fi
echo "===$nowtime ==="